### ISSUE TITLE
Issues launching distance assistant

### ISSUE THREAD

**Issue by lorneeaston** [amzn/distance-assistant#4]
Hi guys,

I am having some problems launching distance-assistant.

I have a machine set up per the instructions, with a GTX1070.

On some executions, the container hangs at:

`[INFO] [1595138723.393518]: Initialized Person Temporal Filter`

On other executions, camera proceeds to initialisation, but the the main script fails:

```
[distance_assistant-2] process has died [pid 51, exit code -11, cmd /home/catkin_ws/src/DistanceAssistant/scripts/distance_assistant_node.py __name:=distance_assistant __log:=/root/.ros/log/1cbd2fce-c986-11ea-8f5d-90f652629971/distance_assistant-2.log].
log file: /root/.ros/log/1cbd2fce-c986-11ea-8f5d-90f652629971/distance_assistant-2*.log
 19/07 06:08:32,896 WARNING [139841173972736] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/07 06:08:35,948 WARNING [139841173972736] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
```

I have attached the ros logs.

[distance_assistant-2.log](https://github.com/amzn/distance-assistant/files/4943320/distance_assistant-2.log)
[master.log](https://github.com/amzn/distance-assistant/files/4943321/master.log)
[roslaunch-arq-distance-assistant-23.log](https://github.com/amzn/distance-assistant/files/4943322/roslaunch-arq-distance-assistant-23.log)
[rosout.log](https://github.com/amzn/distance-assistant/files/4943323/rosout.log)
[rosout-1-stdout.log](https://github.com/amzn/distance-assistant/files/4943324/rosout-1-stdout.log)

**Comment by ericreg-amazon** [comment]
Thank you for your inquiry and for providing the logs.

Our engineers will study the logs and try to help. In the meantime, we found that disconnecting the camera, waiting 5 seconds and connecting it again resolves some hanging issues. We also found that utilizing higher quality USB A-C cables and/or powered USB hubs may alleviate these issues as well.

**Comment by lorneeaston** [comment]
Narrowed down to a segfault when utilising darknet_custom.py. The class DETECTION(Structure) used here is old; the new one can be found here:

https://github.com/AlexeyAB/darknet/blob/master/darknet.py#L56-L68

Updating the class fixed these crashing issues and the application works fine now.

Suggest either updating darknet_custom.py, pinning to a past hash, or vendoring darknet entirely.

```python
class DETECTION(Structure):
    _fields_ = [("bbox", BOX),
                ("classes", c_int),
                ("prob", POINTER(c_float)),
                ("mask", POINTER(c_float)),
                ("objectness", c_float),
                ("sort_class", c_int),
                ("uc", POINTER(c_float)),
                ("points", c_int),
                ("embeddings", POINTER(c_float)),
                ("embedding_size", c_int),
                ("sim", c_float),
                ("track_id", c_int)]
```
